### ISSUE TITLE
puppet apply failed with "undefined method `dig' for"

### ISSUE THREAD

**Issue by madelaney** [sensu/sensu-puppet#1230]
## Description of problem

- What did you do?
Attempting to apply a puppet catalog of sensu::backend
- What happened?
The apply failed with the error message:
```
Error: Failed to apply catalog: undefined method `dig' for #<Hash:0x00000005b55b08>
```
- What did you expect to happen?
The catalog to apply without issue.
- How can someone reproduce the problem?
I'm not sure exactly what's causing the problem but I _believe_ this is due to `bonsai_assets` with the configs supplied in the next section.

## Command used and debugging output

- What does your puppet config look like (including any hiera config)
```ruby 
include ::sensu::backend
```

```yaml
sensu::resources::bonsai_assets:
  sensu/sensu-go-has-contact-filter:
    ensure: present
    version: latest
  sensu/sensu-email-handler:
    ensure: present
    version: latest
  sensu/sensu-aggregate-check:
    ensure: present
    version: latest
  sensu/sensu-slack-handler:
    ensure: present
    version: latest
  sensu/sensu-pagerduty-handler:
    ensure: present
    version: latest
  nixwiz/sensu-go-graphite-handler:
    ensure: present
    version: latest
```
- Is this a masterless or master based puppet setup?
This is a master puppet instance (Puppet 6.4.0)

## Platform and version information

- Your OS: 
Ubuntu 18.04 (amd64)

- Your Ruby version:
2.3.1p112

- Your version of Puppet: 
6.4.0 (Open Source)

- Your version of Sensu: 
```
sudo dpkg -s sensu-go-backend
Package: sensu-go-backend
Status: install ok installed
Priority: optional
Section: Network
Installed-Size: 38511
Maintainer: Sensu, Inc. <support@sensu.io>
Architecture: amd64
Version: 5.18.1-9930
Description: Sensu Go Backend
Homepage: https://sensu.io
```
- Your version of this module: 
4.6.0

**Comment by madelaney** [comment]
I just confirmed, if I remove the key (and values) for `sensu::resources::bonsai_assets` the puppet catalog runs just fine; the bonsai asserts are still live in Sensu(verified via `sensuctl`) just not puppet.

**Comment by madelaney** [comment]
```yaml
sudo -H sensuctl asset list
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/nixwiz/sensu-go-graphite-handler
    io.sensu.bonsai.name: sensu-go-graphite-handler
    io.sensu.bonsai.namespace: nixwiz
    io.sensu.bonsai.tags: graphite, handler
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/nixwiz/sensu-go-graphite-handler
    io.sensu.bonsai.version: 0.4.0
  name: nixwiz/sensu-go-graphite-handler
  namespace: default
spec:
  builds:
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: a9ecc281a6320a92ed4818afddfdaf072be71bee3c24bf34c2fd30af17affd4c9a4140cc8ace451812eeed630412bb216d228040a07640db8330cf90dca13c06
    url: https://assets.bonsai.sensu.io/f198b915d57c582c037429570a24777c75f5e83e/sensu-go-graphite-handler_0.4.0_windows_amd64.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == '386'
    headers: null
    sha512: f8d640ac581907fb3a9032d5c6b690a747b6f72634d6ed895d966b7c2a93f6d55ba1e2716fbdec4c40c2cd2c8abf2c34f52b45de9e064ccba07948e3c5de34e6
    url: https://assets.bonsai.sensu.io/f198b915d57c582c037429570a24777c75f5e83e/sensu-go-graphite-handler_0.4.0_darwin_386.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 4aeed05d1d444ea12ee3509c41d105927f4f1ade1d2a60a49058d08d9ca039109a50b1f9ff795b81c232e767f444a4681a591e64ea2c396bbe38eeb892170b59
    url: https://assets.bonsai.sensu.io/f198b915d57c582c037429570a24777c75f5e83e/sensu-go-graphite-handler_0.4.0_darwin_amd64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'armv7'
    headers: null
    sha512: 31713395d68a0b03ed4e8e835777c8573819d49af40926d6d7c1fe2ce4bcf1adcdafc6fa0b11e44c3946e6dbb4bdf065727048af2d3348259a5b8eafde564561
    url: https://assets.bonsai.sensu.io/f198b915d57c582c037429570a24777c75f5e83e/sensu-go-graphite-handler_0.4.0_linux_armv7.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm64'
    headers: null
    sha512: e6345ccc7c095df022e922c6daf367316a06312fd6498b487ed3129494f8779d6de9060efb8f53c997011263d397bfea13213049dfdb4d10710659358b00d347
    url: https://assets.bonsai.sensu.io/f198b915d57c582c037429570a24777c75f5e83e/sensu-go-graphite-handler_0.4.0_linux_arm64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == '386'
    headers: null
    sha512: a0123d4fcead84ce79a19ecc36b38ed59c18b230e9f284b8ee12ab65ba21a013cd07ca2b0fe9595114975f36b9ae19a6f9c1edd40aac593d8eb9ceaae846298f
    url: https://assets.bonsai.sensu.io/f198b915d57c582c037429570a24777c75f5e83e/sensu-go-graphite-handler_0.4.0_linux_386.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 596ed1f365a45980b37160c74ac67ad830bb62069a705f347a66f27fa091c5eb492359887ac8be7e85cf6690e905e813ae4d331f75ed4cc3b815edfc580606ac
    url: https://assets.bonsai.sensu.io/f198b915d57c582c037429570a24777c75f5e83e/sensu-go-graphite-handler_0.4.0_linux_amd64.tar.gz
  filters: null
  headers: null
---
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-aggregate-check
    io.sensu.bonsai.name: sensu-aggregate-check
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.tags: aggregate, check
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/sensu-aggregate-check
    io.sensu.bonsai.version: 0.0.7
  name: sensu/sensu-aggregate-check
  namespace: default
spec:
  builds:
  - filters:
    - entity.system.os == 'windows'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: dbff92a09a539320e28c45acc64ab6f0bb3c9f1f328910ad1236fd32e36055eb83f5ed42d353aa138bc1d8d1b736e51b50b331a8d36b10957d8301a28a5b0936
    url: https://assets.bonsai.sensu.io/c0e2af9f04f1e4089eb6c9d639ad8f856fca2316/sensu-aggregate-check_0.0.7_windows_amd64.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == '386'
    headers: null
    sha512: 71aeec73b9169a3b266d05c0d8bf0e7f4c2ac468dbb147681b7f7d4c7574ff43891e9c4a993c30434827c06973f80162f40adfa0e849bd17e7480bf7d2e5d4f0
    url: https://assets.bonsai.sensu.io/c0e2af9f04f1e4089eb6c9d639ad8f856fca2316/sensu-aggregate-check_0.0.7_darwin_386.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 79002cba5050ba1b450fa38e1192bc52ae12267feda3879a22559a2794a6e20aeb2ed0e7f944265c811e7f17d2993d36e2680f4e9a80e4b6bc4c5687ce015f5a
    url: https://assets.bonsai.sensu.io/c0e2af9f04f1e4089eb6c9d639ad8f856fca2316/sensu-aggregate-check_0.0.7_darwin_amd64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'armv7'
    headers: null
    sha512: e8f74ad22e168c5e7a35bd5e90efcff9dffe1519d417c53a1f3fea5a16cc616f49ee1c89ee9564fccc29cf66b1400e9e4f9b907bd755672d696c3b04a044b1e5
    url: https://assets.bonsai.sensu.io/c0e2af9f04f1e4089eb6c9d639ad8f856fca2316/sensu-aggregate-check_0.0.7_linux_armv7.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm64'
    headers: null
    sha512: 46372aa32b003b4362b31c05613fed0eea2bdca9b0502b9e057c243c2f3e56601fab5dbf9a0eb87e017c05327c42d41268fc2b7838a77543a8825e81ef108f03
    url: https://assets.bonsai.sensu.io/c0e2af9f04f1e4089eb6c9d639ad8f856fca2316/sensu-aggregate-check_0.0.7_linux_arm64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == '386'
    headers: null
    sha512: 7004791dbb1d2762363b023d14565eea6dbcce4214e2ca57b8c628cdbee6860835bf74b8119fb09576e0eb63f544e83c0f0e24dbc2a5ccc2c6ee7413420736d8
    url: https://assets.bonsai.sensu.io/c0e2af9f04f1e4089eb6c9d639ad8f856fca2316/sensu-aggregate-check_0.0.7_linux_386.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: de6f2f5901b926591749dcd67b86283070867a1c2951beb1421a528ae97269ec7a6e73a35fbbbe6f1e06e8b9147b3aec234254f2208ed193ad465c1da1d92bb0
    url: https://assets.bonsai.sensu.io/c0e2af9f04f1e4089eb6c9d639ad8f856fca2316/sensu-aggregate-check_0.0.7_linux_amd64.tar.gz
  filters: null
  headers: null
---
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-email-handler
    io.sensu.bonsai.name: sensu-email-handler
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.tags: handler
    io.sensu.bonsai.tier: Supported
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/sensu-email-handler
    io.sensu.bonsai.version: 0.4.1
  name: sensu/sensu-email-handler
  namespace: default
spec:
  builds:
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 1eeb00aed9711f5e65f802d32cb957deade520fdf5bd23acd23d7b34875e5b813776c0c81e3dcdc261e8d88ed3bee02ac48f11e7988b6d98caa1fb48aa4de813
    url: https://assets.bonsai.sensu.io/904868a7d9784e46067f211aae195e0f9124ee3b/sensu-email-handler_0.4.1_windows_amd64.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == '386'
    headers: null
    sha512: 0fcc4879f17061a4801508827817958e9c60bf1fd41b45ef28bd5e1d6c37b616cd388fc7d19294d20b72853aca0523e44b7e2ff3462e33695c78c7666d00b151
    url: https://assets.bonsai.sensu.io/904868a7d9784e46067f211aae195e0f9124ee3b/sensu-email-handler_0.4.1_darwin_386.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: a40faacf9fc105c002c4856be780ec15c06d073e64c18e329cbe7907b132e464180e348148e75d590a311b5b9c3a31d617a2ea8d19d7ff54b5c7bcab68ebd0f8
    url: https://assets.bonsai.sensu.io/904868a7d9784e46067f211aae195e0f9124ee3b/sensu-email-handler_0.4.1_darwin_amd64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'armv7'
    headers: null
    sha512: 087e1d8e824f406b2b5eef1f1a13b42097e47f79aca7089e22fe6ddcd93cb6e1a71d681c23a57b3a0deb0e23554bdd852842c9b5232f34cbad335f99d96ddb24
    url: https://assets.bonsai.sensu.io/904868a7d9784e46067f211aae195e0f9124ee3b/sensu-email-handler_0.4.1_linux_armv7.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm64'
    headers: null
    sha512: 19d6faaa6040dd877283f859b6872d27aa48918b86e0c9034387c255c94855cf295aef2dde2c126b756478489880abab1db601ffb20e24363ed1acc9d98dd94b
    url: https://assets.bonsai.sensu.io/904868a7d9784e46067f211aae195e0f9124ee3b/sensu-email-handler_0.4.1_linux_arm64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == '386'
    headers: null
    sha512: 816d10b44ec30746a4b4e97b5e68f37004da349a8b3423c6aa3cfa0d8f4e7efa2e77ef9fab1055c93004a9df32d6f365a7d72c9b49e43ff0c7f247d74934b510
    url: https://assets.bonsai.sensu.io/904868a7d9784e46067f211aae195e0f9124ee3b/sensu-email-handler_0.4.1_linux_386.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 86f0f2d78f5edd324c38e2d227f696d6e61872f00592fc15380df48e3f8511b169099679acc01f04dae7d65ea3c2c9fc4d374ada4465239ca148d8aeaa52b2db
    url: https://assets.bonsai.sensu.io/904868a7d9784e46067f211aae195e0f9124ee3b/sensu-email-handler_0.4.1_linux_amd64.tar.gz
  filters: null
  headers: null
---
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-go-has-contact-filter
    io.sensu.bonsai.name: sensu-go-has-contact-filter
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.tags: eventfilter
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/sensu-go-has-contact-filter
    io.sensu.bonsai.version: 0.2.0
  name: sensu/sensu-go-has-contact-filter
  namespace: default
spec:
  builds:
  - filters: null
    headers: null
    sha512: d07584ddf9d44b3f68102df7038070995d2001e1b826a3fe0d244f6e0fd69b76f29b853a13fcd8841bdb3adebe8a84b3f64247367ef1c9f364c04c5b8ecc16e6
    url: https://assets.bonsai.sensu.io/ff68b326056b1641a1a00ca2fb4f0246bb19a9d0/sensu-go-has-contact-filter_0.2.0.tar.gz
  filters: null
  headers: null
---
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-pagerduty-handler
    io.sensu.bonsai.name: sensu-pagerduty-handler
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.tags: handler
    io.sensu.bonsai.tier: Supported
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/sensu-pagerduty-handler
    io.sensu.bonsai.version: 1.3.2
  name: sensu/sensu-pagerduty-handler
  namespace: default
spec:
  builds:
  - filters:
    - entity.system.os == 'windows'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 10eb353c624fa1853a5b6175366e6ae325315208b2289b1191629004737dbacbfc576f54b95a89560a5226e24aa0438458256b04ac1ffdc9876cf0afdf6441dd
    url: https://assets.bonsai.sensu.io/e6722787284bd20f68d0375ee927aa0ec5d2e57b/sensu-pagerduty-handler_1.3.2_windows_386.tar.gz
  - filters:
    - entity.system.os == 'windows'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 83b51af2254470edbeabf840ae556f113452133f4abbe41e0ce5e0ac37d00262a17646d38ddc23fa16f39706f3506ade902eb1b29429bb0898cfd8c5ce0b0e36
    url: https://assets.bonsai.sensu.io/e6722787284bd20f68d0375ee927aa0ec5d2e57b/sensu-pagerduty-handler_1.3.2_windows_amd64.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == '386'
    headers: null
    sha512: 46826d62f586f935d6a8686da7315105a8161364cbf7665943b3fd349cbe194ab1b5c1f312616014472f2499858f8c595ac5bc56b191df4761632bfa42b1b97c
    url: https://assets.bonsai.sensu.io/e6722787284bd20f68d0375ee927aa0ec5d2e57b/sensu-pagerduty-handler_1.3.2_darwin_386.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 8f14359b5e9f881a495b7b2019b3ecd080421c43c07a96856ee607ab710f57397fd65fdb288cc672eac201e280fa7d87fb2a23f72089665dc0dfc25b27bc64fc
    url: https://assets.bonsai.sensu.io/e6722787284bd20f68d0375ee927aa0ec5d2e57b/sensu-pagerduty-handler_1.3.2_darwin_amd64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'armv7'
    headers: null
    sha512: 77d2a57ce4e806766faf766a592d5623ee31b634d5a118eaf1423a6aec14819cf569bdeb7f557c727f4c3f67a8127b771ff41a3d2e1ce17ffe9935a2bdb00a8a
    url: https://assets.bonsai.sensu.io/e6722787284bd20f68d0375ee927aa0ec5d2e57b/sensu-pagerduty-handler_1.3.2_linux_armv7.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm64'
    headers: null
    sha512: be5a306fcfbec1f3be9ef8f5300dfcbc59425681f4108bf844dc6e7586567e5f5b207f448f335cff0f2bc3816c845bacffa21ed5a124dfb902b7894b4df0acb9
    url: https://assets.bonsai.sensu.io/e6722787284bd20f68d0375ee927aa0ec5d2e57b/sensu-pagerduty-handler_1.3.2_linux_arm64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == '386'
    headers: null
    sha512: 4fea313808cd4e899248f07928386fc84d52cae7013b41d26d6bb9bfac8a0fb4f84cce4ffbeb38d4f8bbb8e4e4e55f72942bfb244d8f2c9f862bcdfb5775da6c
    url: https://assets.bonsai.sensu.io/e6722787284bd20f68d0375ee927aa0ec5d2e57b/sensu-pagerduty-handler_1.3.2_linux_386.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: f0236559b696270ea74ac51274269b8af28ed90901b43e2d13ebed1de34f4faf7a29f06268268a0a41a08721ce67fa0c1f245ad54e444eb06f26fbd87163b687
    url: https://assets.bonsai.sensu.io/e6722787284bd20f68d0375ee927aa0ec5d2e57b/sensu-pagerduty-handler_1.3.2_linux_amd64.tar.gz
  filters: null
  headers: null
---
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-slack-handler
    io.sensu.bonsai.name: sensu-slack-handler
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.tags: ""
    io.sensu.bonsai.tier: Supported
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/sensu-slack-handler
    io.sensu.bonsai.version: 1.2.0
  name: sensu/sensu-slack-handler
  namespace: default
spec:
  builds:
  - filters:
    - entity.system.os == 'windows'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: a48194a62f34b0c31fbeead96bbc99cb90ab67715fe2f55bb300bf9a3e2cce05f6c5b8528ba23d563eaa2af0ee1e8fbd91772fe9cb4cfd8a564c89c8f7995e7c
    url: https://assets.bonsai.sensu.io/65bdb5dd581c59531867691e68ace32762232047/sensu-slack-handler_1.2.0_windows_amd64.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 8760bf3e3885f1de50dc7ae5e949690dbe3d775521b059a2e4865ca6dca4ad8ef2812de13c39ccd6eca9cc557d7205107d038ac5c414bcd713314e494399a7db
    url: https://assets.bonsai.sensu.io/65bdb5dd581c59531867691e68ace32762232047/sensu-slack-handler_1.2.0_darwin_amd64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'armv7'
    headers: null
    sha512: 79840825b3b84ffecc54bcf2841e68c15cf2ca08b00c3ca865e7e97de2544c00203f92a14fa39c0bb39b123117bf3920d8ed9f657b2a8c4f00faad56661df4c2
    url: https://assets.bonsai.sensu.io/65bdb5dd581c59531867691e68ace32762232047/sensu-slack-handler_1.2.0_linux_armv7.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm64'
    headers: null
    sha512: db389297f095fda3543899ff33b0a40cb43e5d36e0ba3b5b2b6a3225c1422b880318b972ec6f16edae1ff0e0e2372c44c139c4c447c9c77bb420440f2462d2b0
    url: https://assets.bonsai.sensu.io/65bdb5dd581c59531867691e68ace32762232047/sensu-slack-handler_1.2.0_linux_arm64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == '386'
    headers: null
    sha512: ae765016a8252dcdf39a773092921e82bb0e75658f49d11d1e6d11636fde1f912e96fc2ff55f9962a60071a75a488bed95899a354cdb1e01c5e6b313d003fc24
    url: https://assets.bonsai.sensu.io/65bdb5dd581c59531867691e68ace32762232047/sensu-slack-handler_1.2.0_linux_386.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: dc4ef7540a6cd07387b8a5b539afd8aa4de9e4b4f7d7bad9dff89018bb1b92fac0555b6bc5f55f048d10c7318b8a4a1efabf8940724a4edf6f6114bc01d5ca14
    url: https://assets.bonsai.sensu.io/65bdb5dd581c59531867691e68ace32762232047/sensu-slack-handler_1.2.0_linux_amd64.tar.gz
  filters: null
  headers: null
```
