### ISSUE TITLE
sensu_check Puppet resource does not support pipelines parameter.

### ISSUE THREAD

**Issue by saulfigueiredo-jam247** [sensu/sensu-puppet#1346]
I'm using:
- puppet --version : 8.7.0
- modules: sensu/sensu 5.11.1 (latest)

I am trying to apply a pipeline to my Sensu check; I've created the pipeline manually and now I'm trying to assign it via my puppet configuration instead of doing it manually

```
  lookup('sensu_checks', {merge => hash}).each |$check_name, $check| {
    sensu_check { $check_name:
      * => $check,
    }
  }
```

```yaml
sensu_checks:
  check_diskspace:
    command: "/opt/sensu-plugins-ruby/embedded/bin/check-disk-usage.rb"
    interval: 60
    subscriptions:
      - common
    handlers:
      - alert_slack
    pipelines:
      - type: Pipeline
        api_version: core/v2
        name: reduce_alerts
    timeout: 10
```

But them I get the error:

```
{"level":"err","message":"no parameter named 'pipelines' (file: /etc/puppetlabs/code/localmodules/roles/manifests/sensu_go/server.pp, line: 39) on Sensu_check[check_diskspace] (file: /etc/puppetlabs/code/localmodules/roles/manifests/sensu_go/server.pp, line: 39) on node sensu-go-qmrf.c.dcb-reference-1285.internal","source":"Puppet","tags":["err"],"file":null,"line":null,"version":1,"@timestamp":"2025-03-24T13:09:31.544847524+00:00"}
```

Am I doing anything wrong ?
