### ISSUE TITLE
Defining checks via hiera

### ISSUE THREAD

**Issue by ghost** [sensu/sensu-puppet#279]
Hello,

In our puppet deployment, we currently manage to pull off all our configuration solely in hiera.  I've managed to get everything defined + functioning in hiera using this module, except I'm unable to define checks.

I've tried configuring it like so, but it doesn't appear to be honored:

```
sensu::check:
    cpucheck:
      command: '/etc/sensu/plugins/check-cpu.rb'
      subscribers: 'cpu'
```

Any tips would be appreciated, going to dig through the code and see if I can figure it out regardless.

Thx!
