### ISSUE TITLE
sensu::checks failing when subscribers are specified

### ISSUE THREAD

**Issue by devopsprosiva** [sensu/sensu-puppet#381]
Hi,

I've the following code in hiera to define a check.

sensu::checks:
  'check_cpu':
    command: '/etc/sensu/plugins/check-cpu.rb -w 75 -c 90'
    handlers: 'mail'
    subscribers: 'all'

After I added the subscribers parameter, the puppet agent run is failing with this error.

Error: undefined method `sort' for nil:NilClass
Error: /Stage[main]/Sensu/Sensu::Check[check_cpu]/Sensu_check[check_cpu]/subscribers: change from  to all failed: undefined method `sort' for nil:NilClass

Thanks,
Siva

**Comment by poolski** [comment]
I think it's to do with the fact that the module expects an array for both `subscribers` and `handlers`, even if it's just one item. 

Check out my JSON structure in #382, make `handlers` and `subscribers` into arrays and try again?

**Comment by devopsprosiva** [comment]
@poolski I'm still getting this error.

```
Error: undefined method `sort' for nil:NilClass
Error: /Stage[main]/Sensu/Sensu::Check[check_http_wiki]/Sensu_check[check_http_wiki]/subscribers: change from  to all failed: undefined method `sort' for nil:NilClass
```

* This is my yaml file with arrays for handlers and subscribers.

```yaml
sensu::checks:
  'check_http_wiki':
    command: '/etc/sensu/plugins/check-http.rb -u http://localhost -s -k -r'
    handlers:
      - 'mail'
    subscribers:
      - 'all'
```
