### ISSUE TITLE
Creating a handler for Librato fails

### ISSUE THREAD

**Issue by rhoml** [sensu/sensu-puppet#484]
I am trying to create a handler for librato metrics using the module and I can't find the right combination for it.  This is the only way it works apparently but sensu-puppet writes a bunch of information that is not needed by the handler

hiera
```
sensu::handlers:
  'librato':
    type: pipe
    source: puppet:///modules/sensu_plugins/handlers/handler-metrics-librato.rb
    config:
      email: 'xx@xx.com'
      api_key: 'XX'
      use_sensu_client_hostname_as_source: false
```

librato.json

```
{
  "handlers": {
    "librato": {
      "command": "/etc/sensu/handlers/handler-metrics-librato.rb",
      "type": "pipe",
      "filters": [

      ],
      "severities": [
        "ok",
        "warning",
        "critical",
        "unknown"
      ]
    }
  },
  "librato": {
    "email": "xx@xx.com",
    "api_key": "xxx"
  }
}
```

In the past I used to send this handler as a file and its configuration too but I would like to use the module instead.

Any hint?
