### ISSUE TITLE
Windows: Provider sensu_gem is not functional on this host

### ISSUE THREAD

**Issue by dzeleski** [sensu/sensu-puppet#607]
Getting this from the most recent commit(https://github.com/sensu/sensu-puppet/commit/614308c51069f37186b56ede98ac0d002c7aa028):
```
Provider sensu_gem is not functional on this host
Source:/Stage[main]/Sensu::Package/Package[sensu-plugin]
File:/etc/puppetlabs/code/environments/production/modules/sensu/manifests/package.pp
Line:86
```

We set the following:
```
         version: '0.26.3-1'
         install_repo: true
         purge: true
         rabbitmq_host: REMOVED
         rabbitmq_password: REMOVED
         rabbitmq_port: 5672
         rabbitmq_vhost: '/sensu'
         use_embedded_ruby: true
         manage_services: true
         manage_user: false
         subscriptions:
            - win_base
```

A second run and everything is fine. This is a server 2012 R2 box.

https://github.com/sensu/sensu-puppet/blob/master/manifests/package.pp#L86

Gems are as follows:
```
PS C:\opt\sensu\embedded\bin> .\gem.bat list

*** LOCAL GEMS ***

amq-protocol (2.0.1)
amqp (1.6.0)
bigdecimal (1.2.0)
childprocess (0.5.8)
em-http-server (0.1.8)
em-worker (0.0.2)
eventmachine (1.2.0.1)
ffi (1.9.14)
io-console (0.4.2)
json (1.7.7)
minitest (4.3.2)
mixlib-cli (1.7.0)
oj (2.14.6)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
sensu (0.26.3)
sensu-extension (1.5.0)
sensu-extensions (1.7.0)
sensu-extensions-debug (1.0.0)
sensu-extensions-json (1.0.0)
sensu-extensions-occurrences (1.1.0)
sensu-extensions-only-check-output (1.0.0)
sensu-extensions-ruby-hash (1.0.0)
sensu-json (2.0.0)
sensu-logger (1.2.0)
sensu-plugin (1.4.2, 1.2.0)
sensu-redis (1.6.0)
sensu-settings (9.2.0)
sensu-spawn (2.2.0)
sensu-transport (6.0.0)
test-unit (2.0.0.0)
```

looking at the provider: https://github.com/sensu/sensu-puppet/blob/master/lib/puppet/provider/package/sensu_gem.rb#L15

Im wondering if the environment var is not being initialized on the first run?
