### ISSUE TITLE
Centos 7 - not properly managing sensu-client service

### ISSUE THREAD

**Issue by jwatroba** [sensu/sensu-puppet#855]
## Description of problem

- What did you do?
**Use this module on CentOS 7 servers**
- What happened?
**If the sensu-client service isn't running, it will not start the process. We have the same config on our CentOS 6 systems and this works fine.**
- What did you expect to happen?
**sensu-client service should be started if it's not running.**
- How can someone reproduce the problem?
**Test sensu-client service management on CentOS7**

## Command used and debugging output

- What does your puppet config look like (including any hiera config)

```yaml
  sensu:
    api: false
    client_custom:
      tags:
        hostname: REDACTED
    install_repo: false
    manage_repo: false
    manage_services: true
    plugins:
    - REDACTED
    rabbitmq_host: REDACTED
    rabbitmq_password: REDACTED
    rabbitmq_vhost: "/sensu"
    sensu_plugin_version: 1.2.0
    subscriptions:
    - common
    use_embedded_ruby: true
    version: 0.26.5-2
```

- Is this a masterless or master based puppet setup?
master based.

## Platform and version information

- Your OS: **CentOS 7**
- Your Ruby version: **2.3.0p0**
- Your version of Puppet: **4.8.0**
- Your version of Sensu: **0.26.5-2**
- Your version of this module: **2.41.0**
